const errors = require('./src/errors')
const handler = require('./src/handling')

//handler.errorFirstCallbackWrong()
/*
try {
    errors.standardErr.range()
} catch (error) {
    console.log('Ha ocurrido un error',err)
}
*/